probe the windows situation real deep

diff --git a/.github/workflows/ci-unittest.yml b/.github/workflows/ci-unittest.yml
--- a/.github/workflows/ci-unittest.yml
+++ b/.github/workflows/ci-unittest.yml
@@ -8,6 +8,69 @@ on:
       - main
 
 jobs:
+  pip-windows-venv-setup-debugging:
+    name: "Test creation of ${{matrix.python}} virtualenv on Windows"
+    strategy:
+      fail-fast: false
+      matrix:
+        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]
+    runs-on: windows-latest
+    defaults:
+      run:
+        shell: bash -e -u -o pipefail {0}
+    steps:
+      - name: Install Python ${{ matrix.python }}
+        uses: actions/setup-python@v5
+        id: py
+        with:
+          python-version: ${{ matrix.python }}
+          update-environment: false
+
+      - name: Log environment before venv creation
+        run: |
+          echo ::group::environment
+          printenv
+          echo ::group::python
+          for tool in python python3 pip '${{ steps.py.outputs.python-path }}'; do
+              if command -v "$tool"; then
+                  "$tool" --version
+              else
+                  printf '%s: not found\n' "$tool"
+              fi
+          done
+
+      - name: Create and check a venv
+        run: |
+          '${{ steps.py.outputs.python-path }}' -m venv venv
+          # I do not understand why the activation script is in a
+          # different location on Windows.
+          if [ ! -d venv/bin ]; then mv venv/Scripts venv/bin; fi
+          source venv/bin/activate
+          echo "::group::venv script"
+          cat venv/bin/activate
+          echo "::group::environment after activation"
+          printenv
+          echo "::group::python after activation"
+          status=0
+          for tool in python python3 pip '${{ steps.py.outputs.python-path }}'; do
+              if command -v "$tool"; then
+                  "$tool" --version
+                  if [ "$tool" != pip ]; then
+                      ver=$("$tool" -c 'import sys; print(".".join(str(x) for x in sys.version_info[:2]))')
+                      if [ "$ver" != '${{ matrix.python }}' ]; then
+                          printf '::error::%s wrong version %s (should be %s)\n' "$tool" "$ver" '${{ matrix.python }}'
+                          status=1
+                      fi
+                  fi
+              else
+                  printf '::error::command "%s" not found\n' "$tool"
+                  status=1
+              fi
+          done
+          echo "::group::pip debug after activation"
+          pip debug
+          exit $status
+
   # Inspired by https://github.com/hynek/build-and-inspect-python-package/
   # but revised for our needs.  In particular, we have some auxiliary
   # files, needed for later steps of this process, that don't belong
@@ -15,71 +78,71 @@ jobs:
   # so those later steps don't need to check out the source tree.
   # In the future, we might want to build a conda package as well
   # as a wheel.
-  build-package:
-    name: Build PDR packages
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check out source tree
-        uses: actions/checkout@v4
-        with:
-          path: src
+  # build-package:
+  #   name: Build PDR packages
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check out source tree
+  #       uses: actions/checkout@v4
+  #       with:
+  #         path: src
 
-      # Future: Any sort of validation of the source code itself,
-      # that only needs to run once, could go here.
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        id: py
-        with:
-          python-version: "3.x" # latest stable
-          update-environment: false
+  #     # Future: Any sort of validation of the source code itself,
+  #     # that only needs to run once, could go here.
+  #     - name: Set up Python
+  #       uses: actions/setup-python@v5
+  #       id: py
+  #       with:
+  #         python-version: "3.x" # latest stable
+  #         update-environment: false
 
-      - name: Prepare build environment
-        run: |
-          '${{ steps.py.outputs.python-path }}' -m venv venv
-          . venv/bin/activate
-          pip install --only-binary :all: --upgrade pip
-          pip install --only-binary :all: \
-              build check-wheel-contents twine wheel
+  #     - name: Prepare build environment
+  #       run: |
+  #         '${{ steps.py.outputs.python-path }}' -m venv venv
+  #         . venv/bin/activate
+  #         pip install --only-binary :all: --upgrade pip
+  #         pip install --only-binary :all: \
+  #             build check-wheel-contents twine wheel
 
-      - name: Build and verify sdist and wheel
-        working-directory: src
-        run: |
-          . ../venv/bin/activate
-          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
-          python -BIm build --outdir=../dist
-          check-wheel-contents ../dist/*.whl
-          python -Im twine check --strict ../dist/*
+  #     - name: Build and verify sdist and wheel
+  #       working-directory: src
+  #       run: |
+  #         . ../venv/bin/activate
+  #         export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
+  #         python -BIm build --outdir=../dist
+  #         check-wheel-contents ../dist/*.whl
+  #         python -Im twine check --strict ../dist/*
 
-      - name: Collect auxiliary files for later stages
-        working-directory: src/.github
-        run: |
-          ZIPFILE=../../dist/scripts-for-jobs.zip
-          zip -r $ZIPFILE scripts
-          zip -j -r $ZIPFILE ../.coveragerc
-          printf '@ .coveragerc\n@=scripts/coveragerc.raw\n' |
-              zipnote -w $ZIPFILE
+  #     - name: Collect auxiliary files for later stages
+  #       working-directory: src/.github
+  #       run: |
+  #         ZIPFILE=../../dist/scripts-for-jobs.zip
+  #         zip -r $ZIPFILE scripts
+  #         zip -j -r $ZIPFILE ../.coveragerc
+  #         printf '@ .coveragerc\n@=scripts/coveragerc.raw\n' |
+  #             zipnote -w $ZIPFILE
 
-      - name: Upload packages
-        uses: actions/upload-artifact@v4
-        with:
-          name: packages
-          path: dist/pdr*
+  #     - name: Upload packages
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: packages
+  #         path: dist/pdr*
 
-      - name: Upload build helpers
-        uses: actions/upload-artifact@v4
-        with:
-          name: scripts-for-jobs
-          path: dist/scripts-for-jobs.zip
-          # this artifact exists only to be input to later jobs,
-          # it does not need to be retained for long
-          retention-days: 1
+  #     - name: Upload build helpers
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: scripts-for-jobs
+  #         path: dist/scripts-for-jobs.zip
+  #         # this artifact exists only to be input to later jobs,
+  #         # it does not need to be retained for long
+  #         retention-days: 1
 
-      - name: Report results
-        run: |
-          ( cd dist
-            printf '\n### Contents of the `packages` artifact\n\n```none\n'
-            shasum -a 256 pdr*
-          ) >> $GITHUB_STEP_SUMMARY
+  #     - name: Report results
+  #       run: |
+  #         ( cd dist
+  #           printf '\n### Contents of the `packages` artifact\n\n```none\n'
+  #           shasum -a 256 pdr*
+  #         ) >> $GITHUB_STEP_SUMMARY
 
   # conda-unit:
   #   name: |
@@ -179,140 +242,140 @@ jobs:
   #         # unmerged coverage analysis data can be ephemeral
   #         retention-days: 1
 
-  pip-unit:
-    name: |
-      Test: ${{matrix.python}}, pip, ${{matrix.os}}, ${{matrix.deps}}
-    needs: build-package
-    strategy:
-      fail-fast: false
-      matrix:
-        # This test exists to verify that the dependencies declared
-        # for pip-based installs are accurate, and this should not be
-        # drastically affected by which python we have, so we don't
-        # test all the python versions in the support range, just the
-        # ends.  Also, this is our opportunity to test against the
-        # upcoming python 3.13, which is not available via conda yet,
-        # but _is_ available from github's own snake collection.
-        os: [ubuntu, macos, windows]
-        python: ["3.13"] #["3.9", "3.12", "3.13-dev"]
-        deps: [minimal] #[minimal, full]
-    runs-on: "${{ matrix.os }}-latest"
-    defaults:
-      run:
-        # so I don't have to write nontrivial script fragments twice
-        shell: bash -e -u -o pipefail {0}
-    steps:
-      - name: Install Python ${{ matrix.python }}
-        uses: actions/setup-python@v5
-        id: py
-        with:
-          python-version: ${{ matrix.python }}
-          update-environment: false
+  # pip-unit:
+  #   name: |
+  #     Test: ${{matrix.python}}, pip, ${{matrix.os}}, ${{matrix.deps}}
+  #   needs: build-package
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       # This test exists to verify that the dependencies declared
+  #       # for pip-based installs are accurate, and this should not be
+  #       # drastically affected by which python we have, so we don't
+  #       # test all the python versions in the support range, just the
+  #       # ends.  Also, this is our opportunity to test against the
+  #       # upcoming python 3.13, which is not available via conda yet,
+  #       # but _is_ available from github's own snake collection.
+  #       os: [ubuntu, macos, windows]
+  #       python: ["3.13"] #["3.9", "3.12", "3.13-dev"]
+  #       deps: [minimal] #[minimal, full]
+  #   runs-on: "${{ matrix.os }}-latest"
+  #   defaults:
+  #     run:
+  #       # so I don't have to write nontrivial script fragments twice
+  #       shell: bash -e -u -o pipefail {0}
+  #   steps:
+  #     - name: Install Python ${{ matrix.python }}
+  #       uses: actions/setup-python@v5
+  #       id: py
+  #       with:
+  #         python-version: ${{ matrix.python }}
+  #         update-environment: false
 
-      - name: Get build helpers
-        uses: actions/download-artifact@v4
-        with:
-          name: scripts-for-jobs
-      - name: Extract build helpers
-        run: unzip scripts-for-jobs.zip
+  #     - name: Get build helpers
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: scripts-for-jobs
+  #     - name: Extract build helpers
+  #       run: unzip scripts-for-jobs.zip
 
-      - name: Get just-built PDR package
-        uses: actions/download-artifact@v4
-        with:
-          name: packages
-          path: dist
+  #     - name: Get just-built PDR package
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: packages
+  #         path: dist
 
-      - name: Install pdr from wheel using pip
-        id: deps
-        run: |
-          if [[ "${{ matrix.deps }}" = minimal ]]; then
-            features=
-          else
-            features="[fits,pvl,pillow,fuzzy]"
-          fi
-          # Need to expand the glob naming the wheel file _before_
-          # it is combined with $features.
-          wheel="$(echo dist/pdr-*-py3-*.whl)"
+  #     - name: Install pdr from wheel using pip
+  #       id: deps
+  #       run: |
+  #         if [[ "${{ matrix.deps }}" = minimal ]]; then
+  #           features=
+  #         else
+  #           features="[fits,pvl,pillow,fuzzy]"
+  #         fi
+  #         # Need to expand the glob naming the wheel file _before_
+  #         # it is combined with $features.
+  #         wheel="$(echo dist/pdr-*-py3-*.whl)"
 
-          '${{ steps.py.outputs.python-path }}' -m venv venv
-          # I do not understand why the activation script is in a
-          # different location on Windows.
-          if [ ! -d venv/bin ]; then mv venv/Scripts venv/bin; fi
-          echo "::group::venv script"
-          cat venv/bin/activate
+  #         '${{ steps.py.outputs.python-path }}' -m venv venv
+  #         # I do not understand why the activation script is in a
+  #         # different location on Windows.
+  #         if [ ! -d venv/bin ]; then mv venv/Scripts venv/bin; fi
+  #         echo "::group::venv script"
+  #         cat venv/bin/activate
 
-          source venv/bin/activate
+  #         source venv/bin/activate
 
-          echo "::group::pip install test helpers"
-          pip install --only-binary :all: pytest pytest-cov
+  #         echo "::group::pip install test helpers"
+  #         pip install --only-binary :all: pytest pytest-cov
 
-          # If this pip command fails *and* Python is a development
-          # version, the issue is probably that some of our
-          # dependencies aren't available; skip the rest of the steps
-          # but don't fail the job.  continue-on-error is
-          # insufficiently nuanced for this rule.
-          echo "::group::pip install pdr and deps"
-          set +e +o pipefail
-          pip install --only-binary :all: "$wheel$features" 2>&1 |
-            tee pip-deps.log
-          pip_status=${PIPESTATUS[0]}
-          python_is_experimental=$(python3 -c 'import sys; print(
-            1 if sys.version_info.releaselevel != "final" else 0
-          )')
-          if [[ $pip_status -eq 0 ]]; then
-            echo "available=true" >> "$GITHUB_OUTPUT"
-            exit 0
-          else
-            echo "available=false" >> "$GITHUB_OUTPUT"
-            if [[ $python_is_experimental -eq 1 ]]; then
-              annote=warning
-              exitcode=0
-            else
-              annote=error
-              exitcode=1
-            fi
-            sed -ne 's/^ERROR: /::'"${annote}"'::/p' < pip-deps.log
-            exit $exitcode
-          fi
+  #         # If this pip command fails *and* Python is a development
+  #         # version, the issue is probably that some of our
+  #         # dependencies aren't available; skip the rest of the steps
+  #         # but don't fail the job.  continue-on-error is
+  #         # insufficiently nuanced for this rule.
+  #         echo "::group::pip install pdr and deps"
+  #         set +e +o pipefail
+  #         pip install --only-binary :all: "$wheel$features" 2>&1 |
+  #           tee pip-deps.log
+  #         pip_status=${PIPESTATUS[0]}
+  #         python_is_experimental=$(python3 -c 'import sys; print(
+  #           1 if sys.version_info.releaselevel != "final" else 0
+  #         )')
+  #         if [[ $pip_status -eq 0 ]]; then
+  #           echo "available=true" >> "$GITHUB_OUTPUT"
+  #           exit 0
+  #         else
+  #           echo "available=false" >> "$GITHUB_OUTPUT"
+  #           if [[ $python_is_experimental -eq 1 ]]; then
+  #             annote=warning
+  #             exitcode=0
+  #           else
+  #             annote=error
+  #             exitcode=1
+  #           fi
+  #           sed -ne 's/^ERROR: /::'"${annote}"'::/p' < pip-deps.log
+  #           exit $exitcode
+  #         fi
 
-      - name: Prepare for testing
-        if: ${{ fromJSON(steps.deps.outputs.available) }}
-        run: |
-          host_os=$(python3 -c 'import os; print(os.name)')
-          scripts/adjust-coverage-config < scripts/coveragerc.raw > coveragerc
+  #     - name: Prepare for testing
+  #       if: ${{ fromJSON(steps.deps.outputs.available) }}
+  #       run: |
+  #         host_os=$(python3 -c 'import os; print(os.name)')
+  #         scripts/adjust-coverage-config < scripts/coveragerc.raw > coveragerc
 
-          # Make the directory tree containing the actual PDR .py
-          # files read-only.  This is because we used to have a lot
-          # of code that wrote scratch files into the PDR source tree
-          # and we don't want it coming back.
-          # We can do this on all platforms for pip-based testing.
-          # Note: on Windows attrib +r has no effect on directories.
-          readonly_dirs="dist venv"
-          host_os=$(python3 -c 'import os; print(os.name)')
-          if [ $host_os = nt ]; then
-            export MSYS2_ARG_CONV_EXCL='*'
-            for f in $readonly_dirs; do
-              icacls "$f" /inheritance:r \
-                  /grant 'CREATOR OWNER:(OI)(CI)(RX,D,DC,WDAC)' \
-                  /grant 'BUILTIN\Users:(OI)(CI)RX'
-              icacls "$f"'\*.*' /reset /t /l /q
-            done
-          else
-            chmod -R a-w $readonly_dirs
-          fi
+  #         # Make the directory tree containing the actual PDR .py
+  #         # files read-only.  This is because we used to have a lot
+  #         # of code that wrote scratch files into the PDR source tree
+  #         # and we don't want it coming back.
+  #         # We can do this on all platforms for pip-based testing.
+  #         # Note: on Windows attrib +r has no effect on directories.
+  #         readonly_dirs="dist venv"
+  #         host_os=$(python3 -c 'import os; print(os.name)')
+  #         if [ $host_os = nt ]; then
+  #           export MSYS2_ARG_CONV_EXCL='*'
+  #           for f in $readonly_dirs; do
+  #             icacls "$f" /inheritance:r \
+  #                 /grant 'CREATOR OWNER:(OI)(CI)(RX,D,DC,WDAC)' \
+  #                 /grant 'BUILTIN\Users:(OI)(CI)RX'
+  #             icacls "$f"'\*.*' /reset /t /l /q
+  #           done
+  #         else
+  #           chmod -R a-w $readonly_dirs
+  #         fi
 
-      - name: Run unit tests
-        if: ${{ fromJSON(steps.deps.outputs.available) }}
-        # See comments on the matching step of the conda-unit job for
-        # explanation.  This step should be the same as that step
-        # *except* that when using pip we have to explicitly activate
-        # the virtualenv.
-        run: |
-          source venv/bin/activate
-          export PYTHONDONTWRITEBYTECODE=1
-          pytest -p no:cacheprovider --basetemp=$PWD/tmp --cov \
-            --cov-config=$PWD/coveragerc --cov-branch --cov-report=term \
-            --import-mode=importlib -r fEsX --pyargs pdr.tests
+  #     - name: Run unit tests
+  #       if: ${{ fromJSON(steps.deps.outputs.available) }}
+  #       # See comments on the matching step of the conda-unit job for
+  #       # explanation.  This step should be the same as that step
+  #       # *except* that when using pip we have to explicitly activate
+  #       # the virtualenv.
+  #       run: |
+  #         source venv/bin/activate
+  #         export PYTHONDONTWRITEBYTECODE=1
+  #         pytest -p no:cacheprovider --basetemp=$PWD/tmp --cov \
+  #           --cov-config=$PWD/coveragerc --cov-branch --cov-report=term \
+  #           --import-mode=importlib -r fEsX --pyargs pdr.tests
 
       # - name: Store coverage data
       #   if: always()
